var l="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)},n="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function r(){r=function(){};n.Symbol||(n.Symbol=t)}var w=0;function t(a){return"jscomp_symbol_"+(a||"")+w++}
function x(){r();var a=n.Symbol.iterator;a||(a=n.Symbol.iterator=n.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&l(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return y(this)}});x=function(){}}function y(a){var c=0;return z(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})}function z(a){x();a={next:a};a[n.Symbol.iterator]=function(){return this};return a}
function A(a,c){x();a instanceof String&&(a+="");var b=0,e={next:function(){if(b<a.length){var f=b++;return{value:c(f,a[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e}for(var B=n,G=["Array","prototype","values"],H=0;H<G.length-1;H++){var I=G[H];I in B||(B[I]={});B=B[I]}var J=G[G.length-1],O=B[J],P=O?O:function(){return A(this,function(a,c){return c})};P!=O&&null!=P&&l(B,J,{configurable:!0,writable:!0,value:P});
var viewer,Q={B:new Cesium.Cartesian3(-1272209.292469148,-4751630.941108344,4063428.939909443),N:new Cesium.Cartesian3(-1289792.3587257643,-4746245.525598164,4051013.2689858945),controller:Cesium.Cartesian3.fromDegrees(-75.62898254394531,40.02804946899414,0),D:Cesium.Cartesian3.fromDegrees(-104.992089,39.761292,1E4),F:Cesium.Cartesian3.fromDegrees(-104.992089,39.761292,2500),C:Cesium.Cartesian3.fromDegrees(-104.999471,39.749217,1800)},R=[];
function S(a){var c=viewer.terrainProvider,b=[Cesium.Cartographic.j(Q[a])],c=Cesium.R(c,11,b);Cesium.T(c,function(){viewer.scene.camera.flyTo({destination:Q[a],orientation:{pitch:0}})})}
function init(){function a(a){return 180/Math.PI*a}function c(a){for(a+="";6>a.length;)a="0"+a;return a}function b(){console.log("Flying back to home position...");C.m()}var e=new Cesium.MapboxImageryProvider({mapId:"mapbox.streets"});new Cesium.BingMapsImageryProvider({url:"//dev.virtualearth.net",mapStyle:Cesium.BingMapsStyle.AERIAL_WITH_LABELS});viewer=new Cesium.Viewer("cesiumContainer",{vrButton:!0,baseLayerPicker:!1,imageryProvider:e,scene3DOnly:!0});viewer.terrainProvider=new Cesium.CesiumTerrainProvider({url:"https://assets.agi.com/stk-terrain/world",
requestVertexNormals:!0});viewer.scene.globe.depthTestAgainstTerrain=!0;viewer.scene.globe.I=!0;viewer.scene.L=!1;Cesium.GeoJsonDataSource.load("data/denver_small.json").then(function(a){viewer.dataSources.add(a);a=a.entities.values;var c=new Cesium.Color(.8,.8,.8,1);console.log("Processing "+a.length+" entities...");for(var f=0;f<a.length;f++){var b=a[f];b.polygon.material=c;b.polygon.outline=!1;b.polygon.height=b._properties.BASEELEV_M-20;b.polygon.extrudedHeight=b._properties.TOPELEV_M-20}console.log("Finished loading buildings...")});
var f=document.createElement("span");f.style.position="absolute";f.style.top="10px";f.style.left="10px";f.style.color="white";f.style["font-family"]="Courier New";f.style["z-index"]="999";f.textContent="Debug";viewer.container.appendChild(f);var C=viewer.scene.camera,M,u,v;(function(){function e(a){a={alpha:!1,preserveDrawingBuffer:a};h=k.getContext("webgl",a);if(!h&&(h=k.getContext("experimental-webgl",a),!h)){VRSamplesUtil.addError("Your browser does not support WebGL.");return}h.clearColor(.1,
.2,.3,1);h.enable(h.DEPTH_TEST);h.enable(h.CULL_FACE);new WGLUStats(h);window.addEventListener("resize",E,!1);E();window.requestAnimationFrame(F)}function K(){for(var N=navigator.getGamepads(),c=0;c<N.length;c++){var d=N[c];if(d&&"OpenVR Gamepad"==d.id&&d.a){if(d.a.position){var b=C.positionCartographic,b=Cesium.Cartesian3.fromDegrees(a(b.longitude),a(b.latitude),b.height-10),b=Cesium.Transforms.eastNorthUpToFixedFrame(b);M||(console.log("Loading the Vive controller model..."),M=viewer.scene.primitives.add(Cesium.s.K({url:"models/Vive_Controller_Body.glb",
modelMatrix:b,scale:1})))}R.push(d)}}}function D(){var a=d.f("left"),c=d.f("right"),b=a.i+c.i,a=a.h+c.h;C.m();console.log("HDM is displaying "+b+" pixels wide and "+a+" pixels high.");b=b/a*window.outerHeight;console.log("Resizing window...");window.resizeTo(b,window.outerHeight);d.O([{source:k}]).then(function(){K()},function(){VRSamplesUtil.addError("requestPresent failed.",2E3)})}function L(){d.g&&d.J().then(function(){},function(){VRSamplesUtil.addError("exitPresent failed.",2E3)})}function T(){E();
d.g?d.c.l&&(VRSamplesUtil.o(m),m=VRSamplesUtil.b("Exit VR","E","media/icons/cardboard64.png","vricon",L)):d.c.l&&(VRSamplesUtil.o(m),m=VRSamplesUtil.b("Enter VR","E","media/icons/cardboard64.png","vricon",D))}function E(){if(d&&d.g){var a=d.f("left"),c=d.f("right");k.width=2*Math.max(a.i,c.i);k.height=Math.max(a.h,c.h)}else k.width=k.offsetWidth*window.devicePixelRatio,k.height=k.offsetHeight*window.devicePixelRatio}function F(){h.clear(h.COLOR_BUFFER_BIT|h.DEPTH_BUFFER_BIT);if(d)if(d.requestAnimationFrame(F),
d.M(g),d.g){var b=viewer.scene.camera;if(g.a&&g.a.orientation){var e=function(a){var b;-.5>=g.a.orientation[a]&&-1<=g.a.orientation[a]&&(b=Math.PI/2-g.a.orientation[a]*Math.PI);.5<g.a.orientation[a]&&1>=g.a.orientation[a]&&(b=2.5*Math.PI-g.a.orientation[a]*Math.PI);0<g.a.orientation[a]&&.5>=g.a.orientation[a]&&(b=Math.PI/2-g.a.orientation[a]*Math.PI);0>g.a.orientation[a]&&-.5<=g.a.orientation[a]&&(b=Math.PI/2-g.a.orientation[a]*Math.PI);return b},p=e(0),q=e(1),e=e(2)-Math.PI/2;0>e&&(e=2*Math.PI+e);
u||(u=q);v||(v=p);if(!isNaN(q)&&!isNaN(p)&&!isNaN(e)){var m=p-v;b.lookRight(q-u);b.lookDown(m);b.setView({orientation:{heading:q,pitch:Math.PI/2-p,roll:e}});v=p;u=q;f.textContent="HMD Heading = "+c(a(q).toFixed(2))+", Camera heading= "+c(a(b.heading).toFixed(2))+", HMD pitch = "+c(a(p).toFixed(2))+", Camera pitch = "+c(a(b.pitch).toFixed(2))+", HMD roll = "+c(a(e).toFixed(2))+", Camera roll = "+c(a(b.roll).toFixed(2))}}R=[];K();viewer.render();d.S()}else b=viewer.scene.camera,h.viewport(0,0,k.width,
k.height),f.textContent="Camera heading = "+c(a(b.heading).toFixed(2))+", Camera pitch = "+c(a(b.pitch).toFixed(2))+", Camera roll = "+c(a(b.roll).toFixed(2)),viewer.render();else window.requestAnimationFrame(F),h.viewport(0,0,k.width,k.height),viewer.render()}var d=null,g=null,m=null,k=viewer.canvas,h=null;navigator.j?(g=new VRFrameData,navigator.j().then(function(a){0<a.length?(d=a[0],d.H=.1,d.G=1024,VRSamplesUtil.b("Fly to Home","F",null,null,b),VRSamplesUtil.b("Fly to Redrocks","D",null,null,
function(){S("redrocks")}),VRSamplesUtil.b("Fly to Denver Downtown","S",null,null,function(){S("denver_downtown_tight")}),VRSamplesUtil.b("Denver Downtown 3D Buildings","A",null,null,function(){S("denver_3d_buildings")}),VRSamplesUtil.b("Reset Pose","R",null,null,function(){d.P()}),d.c.A&&(m=VRSamplesUtil.b("Enter VR","E","media/icons/cardboard64.png","vricon",D)),window.addEventListener("vrdisplaypresentchange",T,!1),window.addEventListener("vrdisplayactivate",D,!1),window.addEventListener("vrdisplaydeactivate",
L,!1),e(d.c.l)):(e(!1),VRSamplesUtil.u("WebVR supported, but no VRDisplays found.",3E3))})):navigator.v?(e(!1),VRSamplesUtil.addError("Your browser supports WebVR but not the latest version. See <a href='http://webvr.info'>webvr.info</a> for more info.")):(e(!1),VRSamplesUtil.addError("Your browser does not support WebVR. See <a href='http://webvr.info'>webvr.info</a> for assistance."))})()}window.init=init;window.flytoLocation=S;window.gotoLocation=function(a){viewer.scene.camera.position=Q[a]};
